import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8');
const game=fs.readFileSync('src/game.js','utf8');
const levels=fs.readFileSync('levels/levels.js','utf8');
const checks=[
 ['version v112',/GAME_VERSION='v112'/.test(game)],
 ['level visibility before apple spawn',/syncWorldGeneration\(n\);\nseedForage\(\)/.test(game)],
 ['hidden-tree apple rejected',/tree\.visible===false/.test(game)&&/apple-hidden-tree/.test(game)&&/br\.parent!==tree/.test(game)],
 ['apple repair keeps new twig',/a\.branch=p\[3\]/.test(game)&&/a\.tree=p\[4\]/.test(game)],
 ['world integrity audit',/runWorldIntegrityAudit/.test(game)&&/worldAudit/.test(game)],
 ['tree apple anchoring',/repairTreeApples/.test(game)&&/apple-off-branch/.test(game)],
 ['rock passage radius',/ROCK_PLAYER_RADIUS=\.31/.test(game)],
 ['family house transparency audit',/family-house-not-transparent/.test(game)],
 ['mounted defense',/function mountedFriendDefense/.test(game)&&/mountedFriendDefense\(\)/.test(game)&&/Друг отогнал/.test(game)],
 ['mounted apple collection',/function canCollectForage\(a\)/.test(game)&&/mountedFriend\|\|/.test(game)&&/function runMountedAppleAudit\(\)/.test(game)&&/__KABANCHIKI_MOUNTED_APPLE_AUDIT__/.test(game)&&/mountedAppleAudit/.test(game)&&/mounted-apple-food/.test(game)],
 ['spawn guard',/function repairAndAuditSpawns\(\)/.test(game)&&/__KABANCHIKI_SPAWN_AUDIT__/.test(game)],
 ['single-source version sync',/loadingVersion/.test(html)&&/window.__KABANCHIKI_VERSION__=GAME_VERSION/.test(game)&&/el.textContent=GAME_VERSION/.test(game)],
 ['cache-busted game module',/src="\.\/src\/game\.js\?v=111"/.test(html)],
 ['html build marker v112',/__KABANCHIKI_BUILD__='v112'/.test(html)],
 ['no-cache document meta',/no-cache, no-store, must-revalidate/.test(html)],
 ['cylindrical tree collision',/function treeTrunkShape/.test(game)&&/function treeTrunkHit/.test(game)],
 ['apple own twig registered',/treeBranchMeshes\.push\(twig\)/.test(game)],
 ['apples only on visible tree twigs',/twig\.parent===tree/.test(game)&&/apple-not-on-tree-twig/.test(game)&&/apple-off-visible-twig/.test(game)&&/tipGap<\.16/.test(game)],
 ['branch-sized tree geometry',/branchGeo=new THREE.CylinderGeometry\(\.09,\.14,1,6\)/.test(game)&&/len=rand\(\.68,1\.08\)/.test(game)],
 ['apples anchored on branches',/function branchApplePoint/.test(game)&&/function appleOnBranch/.test(game)&&/runBranchAppleAudit/.test(game)&&/apple-off-branch/.test(game)],
 ['mounted rock glide and log step',/MOUNTED_ROCK_RADIUS=\.78/.test(game)&&/mountedRockBlocked/.test(game)&&/rideBump/.test(game)&&/if\(mountedFriend\)return e\.n<1/.test(game)&&/runMountedTerrainAudit/.test(game)],
 ['tree-rock real passage audit',/function runTreeRockPassageAudit/.test(game)&&/treeRockPassageAudit/.test(game)&&/tree-rock-visible-gap-blocked/.test(game)],
 ['mounted swept multi-rock audit',/function movePlayerCollisionStep/.test(game)&&/step=\.055/.test(game)&&/MOUNTED_ROCK_RADIUS=\.78/.test(game)&&/mounted-rock-penetrated/.test(game)],
 ['precise rock footprint',/function rockFootprintHit/.test(game)],
 ['jump clears low rocks',/remainingRise/.test(game)&&/top<=py\+remainingRise/.test(game)],
 ['page audio suspension',/visibilitychange/.test(game)&&/audio.suspend/.test(game)],
 ['walking arm swing',/boy.children\[6\]\.rotation\.x/.test(game)],
 ['tree apples',/function appleTreeSpot\(\)/.test(game)&&/py>\.58/.test(game)],
 ['unified collision solver',/function movePlayerCollision\(mx,mz\)/.test(game)&&/function depenetratePlayer\(\)/.test(game)],
 ['collision audit',/function runCollisionAudit\(\)/.test(game)&&/__KABANCHIKI_COLLISION_AUDIT__/.test(game)],
 ['robot collision audit',/function runRobotCollisionTest\(\)/.test(game)&&/__KABANCHIKI_ROBOT_TEST__/.test(game)&&/robotAudit/.test(game)],
 ['robot collision truth geometry',/judge collision by the actual obstacle geometry/.test(game)&&/penetrated=insideFn/.test(game)&&/crossed=crossFn/.test(game)&&/treeTrunkHit\(m,x,z,PLAYER_RADIUS/.test(game)&&/rockEllipse\(m,x,z,ROCK_PLAYER_RADIUS\)/.test(game)],
 ['robot uses rounded rock geometry',/const q=rockShape\(m\)/.test(game)&&/edge=q\.ax\+ROCK_PLAYER_RADIUS/.test(game)&&/rockEllipse\(m,x,z,ROCK_PLAYER_RADIUS\)/.test(game)],
 ['natural log capsule collision',/function logDistance/.test(game)&&/function logFootprintHit/.test(game)&&/function pushOutOfLog/.test(game)&&/CylinderGeometry\(r\*\.78,r,1,7\)/.test(game)],
 ['log physics audit',/function runLogPhysicsAudit/.test(game)&&/__KABANCHIKI_LOG_PHYSICS_AUDIT__/.test(game)&&/logPhysicsAudit/.test(game)&&/log-jump-failed/.test(game)],
 ['rounded rock footprint',/function rockEllipse/.test(game)&&/ax:sx\*\.92/.test(game)],
 ['rock edge orbit audit',/function runRockEdgeAudit\(\)/.test(game)&&/__KABANCHIKI_ROCK_EDGE_AUDIT__/.test(game)&&/rockEdgeAudit/.test(game)&&/rock-invisible-corner/.test(game)],
 ['real rock climb audit',/function runRockClimbAudit\(\)/.test(game)&&/__KABANCHIKI_ROCK_CLIMB_AUDIT__/.test(game)&&/rockClimbAudit/.test(game)&&/rock-climb-failed/.test(game)],
 ['deterministic rock corridor audit',/function runRockCorridorAudit\(\)/.test(game)&&/__KABANCHIKI_ROCK_CORRIDOR_AUDIT__/.test(game)&&/rockCorridorAudit/.test(game)],
 ['ballistic rock entry',/remainingRise=vy>0\?\(vy\*vy\)\/\(2\*18\)/.test(game)],
 ['branches use geometry collision',/circleHitsTreeGeometry/.test(game)&&/treeSolidMeshes/.test(game)],
 ['external game module',/src="\.\/src\/game\.js(?:\?v=\d+)?"/.test(html)],
 ['no giant inline game module',!/<script type="module">[\s\S]{5000,}<\/script>/.test(html)],
 ['five level metadata entries',(levels.match(/id:/g)||[]).length===5],
 ['forest remaster layer',/const forestVisual=new THREE.Group/.test(game)],
 ['layered forest ground',/const forestGround=new THREE.Group/.test(game)],
 ['organic tree geometry',/CylinderGeometry\(.46,.68,1,7\)/.test(game)],
 ['clustered tree crowns',/const crownN=Math.floor/.test(game)],
 ['instanced forest grass',/new THREE.InstancedMesh/.test(game)],
 ['cinematic tone mapping',/ACESFilmicToneMapping/.test(game)],
 ['Timur remaster',/boy\.userData\.visualRemaster=true/.test(game)],
 ['boar remaster',/g\.userData\.visualRemaster=true/.test(game)],
 ['boar tusks and ears',/tuskMat/.test(game)&&/ConeGeometry\(.19,.42,4\)/.test(game)],
 ['animated boar tail',/tailPivot\.rotation\.y/.test(game)],
 ['lake remaster layer',/const lakeVisual=new THREE.Group/.test(game)],
 ['animated lake ripples',/rippleA\.rotation\.z/.test(game)&&/waterRippleMatA\.opacity/.test(game)],
 ['lake lilies and reeds',/lilyMat/.test(game)&&/reedTipMat/.test(game)],
 ['lake sun glint',/const lakeGlint=new THREE.Mesh/.test(game)],
 ['game loop',/function loop\(now\)/.test(game)],
 ['friend portal persistence',/const carriedFriend=friend,carriedFriendHP=friendHP/.test(game)],
 ['difficulty system',/const DIFF_CONFIG=\[/.test(game)],
 ['automation hook',/__KABANCHIKI_TEST__/.test(game)],
 ['audio toggles',/toggleMusic/.test(html)&&/toggleSfx/.test(html)&&/musicEnabled/.test(game)&&/sfxEnabled/.test(game)],
 ['lake evening restored',/0xe59a78/.test(game)],
 ['boss knockback',game.includes('отбрасывает его')&&game.includes('target.stagger=Math.max')],
 ['result dedup',game.includes('resultGlobalSaved')&&game.includes('resultLocalSaved')&&game.includes('resultSaving')],
 ['global leaderboard config',game.includes('SUPABASE_URL')&&game.includes('submitGlobalResult')&&game.includes('globalStatsHtml')]
];
let bad=0;for(const [n,ok] of checks){console.log(`${ok?'✓':'✗'} ${n}`);if(!ok)bad++}
if(bad)process.exit(1);

