import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8');
const game=fs.readFileSync('src/game.js','utf8');
const levels=fs.readFileSync('levels/levels.js','utf8');
const checks=[
 ['lake has no mushrooms',/level===2&&type==='mushroom'/.test(game)&&/lake-mushroom/.test(game)],
 ['apples outside tree trunks',/function appleOutsideOwnTrunk/.test(game)&&/apple-inside-tree/.test(game)&&/startR=trunkR\+\.08/.test(game)],
 ['road clear of solid scenery',/function roadClearForRadius/.test(game)&&/road-rock/.test(game)&&/road-mountain/.test(game)&&/road-lair/.test(game)&&/safeSolidScenerySpot/.test(game)],
 ['forage road runtime audit',/function runForageRoadAudit/.test(game)&&/__KABANCHIKI_FORAGE_ROAD_AUDIT__/.test(game)&&/forageRoadAudit/.test(game)],
 ['version v128',/GAME_VERSION='v128'/.test(game)],
 ['level visibility before apple spawn',/syncWorldGeneration\(n\);\nseedForage\(\)/.test(game)],
 ['hidden-tree apple rejected',/tree\.visible===false/.test(game)&&/apple-hidden-tree/.test(game)&&/br\.parent!==tree/.test(game)],
 ['apple repair keeps new twig',/a\.branch=p\[3\]/.test(game)&&/a\.tree=p\[4\]/.test(game)],
 ['world integrity audit',/runWorldIntegrityAudit/.test(game)&&/worldAudit/.test(game)],
 ['tree apple anchoring',/repairTreeApples/.test(game)&&/apple-off-branch/.test(game)],
 ['rock passage radius',/ROCK_PLAYER_RADIUS=\.31/.test(game)],
 ['family house cutaway audit',/family-house-cutaway-not-active-at-door/.test(game)],
 ['family house reveals at doorway',/function familyHouseRevealAt/.test(game)&&/family-house-cutaway-not-active-at-door/.test(game)&&/family-house-door-reveal-zone-missing/.test(game)],
 ['family window attached to hideout',/familyWindow\.userData\.familyWindow=true/.test(game)&&/family-window-detached/.test(game)&&/family-window-off-wall/.test(game)],
 ['mounted defense',/function mountedFriendDefense/.test(game)&&/mountedFriendDefense\(\)/.test(game)&&/Друг отогнал/.test(game)],
 ['mounted apple collection',/function canCollectForage\(a\)/.test(game)&&/mountedFriend\|\|/.test(game)&&/function runMountedAppleAudit\(\)/.test(game)&&/__KABANCHIKI_MOUNTED_APPLE_AUDIT__/.test(game)&&/mountedAppleAudit/.test(game)&&/mounted-apple-food/.test(game)],
 ['spawn guard',/function repairAndAuditSpawns\(\)/.test(game)&&/__KABANCHIKI_SPAWN_AUDIT__/.test(game)],
 ['single-source version sync',/loadingVersion/.test(html)&&/window.__KABANCHIKI_VERSION__=GAME_VERSION/.test(game)&&/el.textContent=GAME_VERSION/.test(game)],
 ['cache-busted game module',/src="\.\/src\/game\.js\?v=128"/.test(html)],
 ['module cache version matches game',(()=>{const gv=game.match(/GAME_VERSION='(v\d+)'/)?.[1],raw=html.match(/src="\.\/src\/game\.js\?v=(\d+)"/)?.[1],mv=raw?'v'+raw:undefined,bv=html.match(/__KABANCHIKI_BUILD__='(v\d+)'/)?.[1];return gv==='v128'&&gv===mv&&gv===bv})()],
 ['html build marker v128',/__KABANCHIKI_BUILD__='v128'/.test(html)],
 ['no-cache document meta',/no-cache, no-store, must-revalidate/.test(html)],
 ['cylindrical tree collision',/function treeTrunkShape/.test(game)&&/function treeTrunkHit/.test(game)],
 ['apple own twig registered',/treeBranchMeshes\.push\(twig\)/.test(game)],
 ['reachable fruit twig height',/const branchY=rand\(1\.28,1\.68\)/.test(game)&&/if\(appleY>2\.08\)/.test(game)&&/apple-too-high/.test(game)],
 ['apples only on visible tree twigs',/twig\.parent===tree/.test(game)&&/apple-not-on-tree-twig/.test(game)&&/apple-off-visible-twig/.test(game)&&/tipGap<\.16/.test(game)],
 ['branch-sized tree geometry',/branchGeo=new THREE.CylinderGeometry\(\.09,\.14,1,6\)/.test(game)&&/len=rand\(\.68,1\.08\)/.test(game)],
 ['apples anchored on branches',/function branchApplePoint/.test(game)&&/function appleOnBranch/.test(game)&&/runBranchAppleAudit/.test(game)&&/apple-off-branch/.test(game)],
 ['mounted rock glide and log step',/MOUNTED_ROCK_RADIUS=\.78/.test(game)&&/mountedRockBlocked/.test(game)&&/rideBump/.test(game)&&/if\(mountedFriend\)return e\.n<1/.test(game)&&/runMountedTerrainAudit/.test(game)],
 ['mounted depenetration uses rider radius',/riding=!!mountedFriend,bodyRadius=riding\?MOUNTED_ROCK_RADIUS:ROCK_PLAYER_RADIUS/.test(game)&&/bodyRadius\+\.015,!riding/.test(game)],
 ['on-foot rock depenetration stays jump-aware',/bodyRadius\+\.015,!riding/.test(game)&&/const riding=!!mountedFriend/.test(game)],
 ['cluster-safe environment audit',/intentionally clustered mountain\/lair prop/.test(game)&&/invalid-\$\{o\.type\}-circle/.test(game)&&!/sealed-\$\{o\.type\}/.test(game)],
 ['tree-rock real passage audit',/function runTreeRockPassageAudit/.test(game)&&/treeRockPassageAudit/.test(game)&&/tree-rock-visible-gap-blocked/.test(game)],
 ['mounted swept multi-rock audit',/function movePlayerCollisionStep/.test(game)&&/step=\.055/.test(game)&&/MOUNTED_ROCK_RADIUS=\.78/.test(game)&&/mounted-rock-penetrated/.test(game)],
 ['mounted cluster settles after every sweep slice',/if\(mountedFriend\)\{[\s\S]*depenetratePlayer\(\)/.test(game)&&/mountedFriend\?14:6/.test(game)],
 ['precise rock footprint',/function rockFootprintHit/.test(game)],
 ['jump clears low rocks',/remainingRise/.test(game)&&/top<=py\+remainingRise/.test(game)],
 ['page audio suspension',/visibilitychange/.test(game)&&/audio.suspend/.test(game)],
 ['walking arm swing',/boy.children\[6\]\.rotation\.x/.test(game)],
 ['tree apples',/function appleTreeSpot\(\)/.test(game)&&/py>\.58/.test(game)],
 ['unified collision solver',/function movePlayerCollision\(mx,mz\)/.test(game)&&/function depenetratePlayer\(\)/.test(game)],
 ['collision audit',/function runCollisionAudit\(\)/.test(game)&&/__KABANCHIKI_COLLISION_AUDIT__/.test(game)],
 ['robot collision audit',/function runRobotCollisionTest\(\)/.test(game)&&/__KABANCHIKI_ROBOT_TEST__/.test(game)&&/robotAudit/.test(game)],
 ['robot collision truth geometry',/judge collision by the actual obstacle geometry/.test(game)&&/penetrated=insideFn/.test(game)&&/crossed=crossFn/.test(game)&&/treeTrunkHit\(m,x,z,PLAYER_RADIUS/.test(game)&&/rockEllipse\(m,x,z,ROCK_PLAYER_RADIUS\)/.test(game)],
 ['robot uses rounded rock geometry',/const q=rockShape\(m\)/.test(game)&&/edge=q\.ax\+ROCK_PLAYER_RADIUS/.test(game)&&/rockEllipse\(m,x,z,ROCK_PLAYER_RADIUS\)/.test(game)],
 ['natural log capsule collision',/function logDistance/.test(game)&&/function logFootprintHit/.test(game)&&/function pushOutOfLog/.test(game)&&/CylinderGeometry\(r\*\.78,r,1,7\)/.test(game)],
 ['log physics audit',/function runLogPhysicsAudit/.test(game)&&/__KABANCHIKI_LOG_PHYSICS_AUDIT__/.test(game)&&/logPhysicsAudit/.test(game)&&/log-jump-failed/.test(game)],
 ['rounded rock footprint',/function rockEllipse/.test(game)&&/ax:sx\*\.92/.test(game)],
 ['rock edge orbit audit',/function runRockEdgeAudit\(\)/.test(game)&&/__KABANCHIKI_ROCK_EDGE_AUDIT__/.test(game)&&/rockEdgeAudit/.test(game)&&/rock-invisible-corner/.test(game)],
 ['real rock climb audit',/function runRockClimbAudit\(\)/.test(game)&&/__KABANCHIKI_ROCK_CLIMB_AUDIT__/.test(game)&&/rockClimbAudit/.test(game)&&/rock-climb-failed/.test(game)],
 ['deterministic rock corridor audit',/function runRockCorridorAudit\(\)/.test(game)&&/__KABANCHIKI_ROCK_CORRIDOR_AUDIT__/.test(game)&&/rockCorridorAudit/.test(game)],
 ['ballistic rock entry',/remainingRise=vy>0\?\(vy\*vy\)\/\(2\*18\)/.test(game)],
 ['branches use geometry collision',/circleHitsTreeGeometry/.test(game)&&/treeSolidMeshes/.test(game)],
 ['external game module',/src="\.\/src\/game\.js(?:\?v=\d+)?"/.test(html)],
 ['no giant inline game module',!/<script type="module">[\s\S]{5000,}<\/script>/.test(html)],
 ['five level metadata entries',(levels.match(/id:/g)||[]).length===5],
 ['forest remaster layer',/const forestVisual=new THREE.Group/.test(game)],
 ['layered forest ground',/const forestGround=new THREE.Group/.test(game)],
 ['organic tree geometry',/CylinderGeometry\(.46,.68,1,7\)/.test(game)],
 ['clustered tree crowns',/const crownN=Math.floor/.test(game)],
 ['instanced forest grass',/new THREE.InstancedMesh/.test(game)],
 ['cinematic tone mapping',/ACESFilmicToneMapping/.test(game)],
 ['Timur remaster',/boy\.userData\.visualRemaster=true/.test(game)],
 ['boar remaster',/g\.userData\.visualRemaster=true/.test(game)],
 ['boar tusks and ears',/tuskMat/.test(game)&&/ConeGeometry\(.19,.42,4\)/.test(game)],
 ['animated boar tail',/tailPivot\.rotation\.y/.test(game)],
 ['lake remaster layer',/const lakeVisual=new THREE.Group/.test(game)],
 ['animated lake ripples',/rippleA\.rotation\.z/.test(game)&&/waterRippleMatA\.opacity/.test(game)],
 ['lake lilies and reeds',/lilyMat/.test(game)&&/reedTipMat/.test(game)],
 ['lake sun glint',/const lakeGlint=new THREE.Mesh/.test(game)],
 ['game loop',/function loop\(now\)/.test(game)],
 ['friend portal persistence',/const carriedFriend=friend,carriedFriendHP=friendHP/.test(game)],
 ['difficulty system',/const DIFF_CONFIG=\[/.test(game)],
 ['automation hook',/__KABANCHIKI_TEST__/.test(game)],
 ['audio toggles',/toggleMusic/.test(html)&&/toggleSfx/.test(html)&&/musicEnabled/.test(game)&&/sfxEnabled/.test(game)],
 ['lake evening restored',/0xe59a78/.test(game)],
 ['boss knockback',game.includes('отбрасывает его')&&game.includes('target.stagger=Math.max')],
 ['result dedup',game.includes('resultGlobalSaved')&&game.includes('resultLocalSaved')&&game.includes('resultSaving')],
 ['global leaderboard config',game.includes('SUPABASE_URL')&&game.includes('submitGlobalResult')&&game.includes('globalStatsHtml')],
 ['explicit family roles',/function makeFamily\(x,z,forcedRole=null\)/.test(game) && /familyRoles=\{2:\[0\],3:\[1\],4:\[2,3\]\}/.test(game)],
 ['random safe family placement audit',/function runFamilyPlacementAudit\(\)/.test(game) && /family-on-road/.test(game) && /family-in-obstacle/.test(game)],
 ['dad remains inside moving hideout',/dadLocal=new THREE\.Vector3\(-\.65,0,-1\.25\)/.test(game) && /family-dad-not-in-hideout/.test(game)],
 ['hideout fixed in far village corner',/farDadPlot=\[30,-31\]/.test(game)&&/family-hideout-not-in-far-corner/.test(game)],
 ['dad visible before collection',/family-dad-not-visible/.test(game) && /family-house-cutaway-not-active-at-door/.test(game)],
 ['mounted geometry uses global all-rock footprint',/function mountedRockFreeAt\(x,z,slack=0\)[\s\S]*rockEllipse\(m,x,z,MOUNTED_ROCK_RADIUS\+slack\)\.n<1/.test(game)],
 ['mounted sweep rolls back only to last globally safe footprint',/mountedRockFreeAt\(safeX,safeZ,\.004\)[\s\S]*boy\.position\.x=safeX;boy\.position\.z=safeZ/.test(game)],
 ['mounted real-rock audit starts globally clear',game.includes('begin every real-rock probe from a globally valid rider footprint')],
 ['branch traversal uses real swept crossing',/function runBranchTraversalAudit\(\)[\s\S]*movePlayerCollision\(-nx\*\.065\*dir,-nz\*\.065\*dir\)[\s\S]*foot-branch-not-crossed/.test(game)],
 ['branch crossing has physical bump',/function branchStepHeightAt\(x,z\)[\s\S]*logDistance\(o,x,z\)[\s\S]*foot-branch-no-bump/.test(game)],
 ['failed runs submit globally',!/if\(!win\)return \{ok:false,localOnly:true\}/.test(game)&&/if\(!resultGlobalSaved\)global=await submitGlobalResult\(name\)/.test(game)],
 ['branch audit forest-only',/if\(level!==1\|\|!forestVisual\.visible\)return \{ok:true,issues,tested:0,samples,level\}/.test(game)],
 ['branch audit crosses capsule normal',/const c=Math\.cos\(o\.yaw\),sn=Math\.sin\(o\.yaw\),nx=-sn,nz=c/.test(game)],
 ['live foot branch step-up',/const branchTop=branchStepHeightAt\(boy\.position\.x,boy\.position\.z\);[\s\S]{0,180}py=branchTop/.test(game)],

 ['generic camera occlusion fade',/setObjectCameraFade/.test(game)&&/occluderRoots=/.test(game)&&/houseObjects/.test(game)&&/rockPositions/.test(game)&&/ridgeObjects/.test(game)],
 ['dad house inside-shell reveal',/insideShell=q\.x>-2\.28/.test(game)&&/familyHouseRevealAt/.test(game)],
 ['dad house warm light stays on',/hideDoorGlow\.visible=\(n===3\)/.test(game)&&/hideDoorGlow\.intensity=n===3\?16:0/.test(game)&&/family-house-light-not-persistent/.test(game)],
 ['dad house shell is isolated and fully audited',/familyHouseShell/.test(game)&&/dad-house-shell-not-fully-transparent|family-house-cutaway-not-active-at-door/.test(game)&&/family-dad-inherited-transparency/.test(game)],
 ['runtime occlusion visibility audit',/__KABANCHIKI_OCCLUSION_AUDIT__/.test(game)&&/dad-house-shell-not-fully-transparent|family-house-cutaway-not-active-at-door/.test(game)],
 ['boss minions have three-hit combat',/function hitBossMinion\(target,ax,az,al\)/.test(game)&&/target\.hp=Math\.max\(0,\(target\.hp\?\?3\)-1\)/.test(game)&&/m\.isMinion=true;m\.hp=3;m\.maxHp=3/.test(game)],
 ['boss minions keep peaceful feeding path',/if\(f\.isBoss\)[\s\S]*else\{statsData\.fed\+\+;foes\.splice/.test(game)],
 ['mounted and foot attacks both damage minions',(game.match(/else if\(target\.isMinion\)\{hitBossMinion\(target,ax,az,al\)\}/g)||[]).length===2],
 ['minion defeat flees instead of death',/sendBoarAway\(target,'defeated'\)[\s\S]*Миньон получил 3 удара/.test(game)],
 ['boss death starts five second finale',/function onBossDefeated\(boss\)/.test(game)&&/bossVictoryTimer=5/.test(game)&&/function finishBossVictory\(\)/.test(game)],
 ['boss victory ignores living minions',/for\(const m of \[\.\.\.foes\]\)[\s\S]*m\.isMinion[\s\S]*sendBoarAway\(m,'boss-defeated'\)/.test(game)&&!/level===5&&foes\.length===0&&!win/.test(game)],
 ['boss fireworks before outro',/function spawnVictoryFirework\(\)/.test(game)&&/bossFireworkTimer=\.32/.test(game)&&/playCinematic\('outro'/.test(game)],
 ['boss fireballs active from start',/boss\.attackCd-=dt;const bossBoyDist/.test(game)&&!/if\(boss\.hp<=2\)\{boss\.attackCd/.test(game)],
 ['boss stronger combat lighting',/boss\.rageLight\.intensity=8\+eyePower\*13/.test(game)&&/boss\.crownLight\.intensity=7\+eyePower\*10/.test(game)],
 ['boss moon visible and lit',/moon\.visible=\(n===5\)/.test(game)&&/moonLight\.intensity=n===5\?\.62:0/.test(game)],
 ['family faces Timur',/f\.g\.rotation\.y=Math\.atan2\(boy\.position\.x-f\.g\.position\.x,boy\.position\.z-f\.g\.position\.z\)/.test(game)],
];
let bad=0;for(const [n,ok] of checks){console.log(`${ok?'✓':'✗'} ${n}`);if(!ok)bad++}
if(bad)process.exit(1);


