// Three instanced draws for perching summer birds and migrating autumn flocks.
export class BirdLife{
 constructor(T,scene,mobile){this.T=T;this.count=mobile?12:24;this.root=new T.Group();scene.add(this.root);const mat=new T.MeshLambertMaterial({color:0x2d383b}),body=new T.SphereGeometry(1,7,5);body.scale(.11,.075,.22);this.body=new T.InstancedMesh(body,mat,this.count);this.left=new T.InstancedMesh(new T.BoxGeometry(.3,.025,.13),mat,this.count);this.right=new T.InstancedMesh(this.left.geometry,mat,this.count);this.root.add(this.body,this.left,this.right);for(const m of this.root.children){m.frustumCulled=false;m.castShadow=false}this.d=new T.Object3D();this.body.count=this.left.count=this.right.count=0;this.perches=[];this.season='summer';this.time=0;this.positions=[];this.scared=new Map()}
 reset(season,trees,roofs=[]){this.season=season;this.time=0;this.positions=[];this.scared.clear();this.root.visible=season!=='winter';this.perches=trees.slice(0,40).map(t=>{t.updateWorldMatrix(true,true);const box=new this.T.Box3().setFromObject(t);return {x:t.position.x+.45,z:t.position.z+.3,y:box.max.y+.08}});this.perches=roofs.concat(this.perches);this.body.count=this.left.count=this.right.count=season==='autumn'?this.count:Math.min(this.count,this.perches.length)}
 update(dt,terrain){if(!this.root.visible||!this.body.count)return;this.time+=Math.max(0,Number.isFinite(dt)?dt:0);this.positions??=[];this.scared??=new Map();const lerp=(a,b,t)=>a+(b-a)*t,smooth=t=>{t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)};
 for(let i=0;i<this.body.count;i++){let x,y,z,yaw,flap,scale=1;if(this.season==='autumn'){const group=i%2,rank=Math.floor(i/2),side=rank%2?1:-1,row=Math.ceil(rank/2),travel=(this.time*.8+group*48)%120;x=-60+travel-row*1.4;z=(group?14:-12)+side*row*1.7;y=14+group*3+Math.sin(this.time*.9+i)*.15;yaw=Math.PI/2;flap=Math.sin(this.time*11+i)*.7;scale=1.7}else if(this.season==='spring'&&this.time<28){const row=Math.ceil(i/2),side=i%2?1:-1,arrival=this.perches[i%this.perches.length];const flight=Math.min(1,this.time/18),land=smooth((this.time-18)/10);x=lerp(side*row*1.4,arrival.x,land);z=lerp(60-flight*48+row*1.4,arrival.z,land);y=lerp(16+Math.sin(this.time+i)*.15,arrival.y,land);yaw=Math.atan2(arrival.x-x,arrival.z-z);flap=Math.sin(this.time*14+i)*.7}else{const clock=(this.season==='spring'?Math.max(0,this.time-28):this.time)/(20+i%7)+(this.season==='spring'?0:i*.137),cycle=Math.floor(clock),a=this.perches[(i+cycle*7)%this.perches.length],b=this.perches[(i+(cycle+1)*7)%this.perches.length],phase=clock%1,g={x:a.x+1.2,z:a.z+.7,y:terrain(a.x+1.2,a.z+.7)+.09};if(phase<.18){({x,y,z}=a);yaw=i;flap=.05}else if(phase<.4){const k=smooth((phase-.18)/.22);x=lerp(a.x,g.x,k);z=lerp(a.z,g.z,k);y=lerp(a.y,g.y,k)+Math.sin(k*Math.PI)*.6;yaw=Math.atan2(g.x-a.x,g.z-a.z);flap=Math.sin(this.time*17+i)*.8}else if(phase<.55){({x,y,z}=g);yaw=i+Math.sin(this.time*2)*.2;flap=.08}else if(phase<.87){const k=smooth((phase-.55)/.32);x=lerp(g.x,b.x,k);z=lerp(g.z,b.z,k);y=lerp(g.y,b.y,k)+Math.sin(k*Math.PI)*2;yaw=Math.atan2(b.x-g.x,b.z-g.z);flap=Math.sin(this.time*15+i)*.8}else{({x,y,z}=b);yaw=i;flap=.05}}
 const until=this.scared.get(i)||0;if(until>this.time){const flee=3-(until-this.time);x+=Math.sin(i*2.4)*flee*2;z+=Math.cos(i*2.4)*flee*2;y+=Math.sin(Math.min(1,flee/3)*Math.PI)*3+1;flap=Math.sin(this.time*20+i)*.9}else this.scared.delete(i);this.positions[i]={index:i,x,y,z};const d=this.d;d.position.set(x,y,z);d.rotation.set(0,yaw,0);d.scale.setScalar(scale);d.updateMatrix();this.body.setMatrixAt(i,d.matrix);for(const [side,mesh] of [[-1,this.left],[1,this.right]]){d.position.set(x+Math.cos(yaw)*side*.17*scale,y+.025,z-Math.sin(yaw)*side*.17*scale);d.rotation.set(0,yaw,side*flap);d.updateMatrix();mesh.setMatrixAt(i,d.matrix)}}for(const m of this.root.children)m.instanceMatrix.needsUpdate=true}
 nearest(x,z,r,maxY=Infinity){if(!this.root.visible)return null;let best=null,d=r;for(const b of this.positions){if(!b||b.y>maxY||this.scared.has(b.index))continue;const n=Math.hypot(b.x-x,b.z-z);if(n<d){best=b;d=n}}return best}
 scare(index){this.scared.set(index,this.time+3)}
 inspect(){return {season:this.season,visible:this.root.visible,count:this.root.visible?this.body.count:0,perches:this.perches.length}}
}
