import {findGridPath} from './navigation.js?v=164';
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export class CatLife{
 constructor(T,scene){this.T=T;this.root=new T.Group();scene.add(this.root);this.root.visible=false;this.cats=[this.model(0),this.model(1)];this.time=0;this.stats={chases:0,scratches:0,roofVisits:0}}
 model(index){const T=this.T,g=new T.Group(),fur=new T.MeshLambertMaterial({color:index?0xc98445:0x555b65}),white=new T.MeshLambertMaterial({color:0xe8ded1}),pink=new T.MeshLambertMaterial({color:0xd99898}),black=new T.MeshBasicMaterial({color:0x16261b});this.root.add(g);const box=(mat,x,y,z,w,h,d)=>{const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);g.add(m);return m};const body=box(fur,0,.4,0,.38,.34,.75),head=box(fur,0,.65,.42,.4,.36,.32);box(white,0,.31,.26,.26,.24,.18);for(const x of [-.13,.13]){const ear=new T.Mesh(new T.ConeGeometry(.11,.2,4),fur);ear.position.set(x,.94,.4);g.add(ear);box(black,x,.7,.59,.07,.065,.025)}box(pink,0,.59,.602,.07,.05,.025);const legs=[];for(const x of [-.13,.13])for(const z of [-.25,.25])legs.push(box(z>0?white:fur,x,.17,z,.12,.32,.13));const tail=new T.Group();tail.position.set(0,.48,-.4);g.add(tail);const tm=new T.Mesh(new T.BoxGeometry(.09,.09,.64),fur);tm.position.z=-.26;tail.add(tm);tail.rotation.x=-.5;return {g,body,head,legs,tail,index,state:index?'play':'roof',timer:0,path:[],routeAge:0,home:0,jump:null,target:null,steps:0,scratchCount:0,chaseCount:0}}
 reset(level,houses,objects,terrain,blocked){this.root.visible=level===3;this.time=0;this.terrain=terrain;this.blocked=blocked;this.houses=houses;this.objects=objects;this.stats={chases:0,scratches:0,roofVisits:0};if(!this.root.visible)return;for(const c of this.cats){c.path=[];c.timer=c.index?0:8;c.jump=null;c.target=null;c.scratchCount=0;c.chaseCount=0;c.roofScratched=false;c.home=0;c.state=c.index?'play':'roof';const h=houses[0];c.g.position.set(h.x+(c.index?5:0),c.index?terrain(h.x+5,h.z):h.y,h.z);c.steps=0}}
 point(c){return {x:c.g.position.x,y:c.g.position.y,z:c.g.position.z}}
 leap(c,to,then,duration=1){c.jump={from:this.point(c),to,t:0,duration,then};c.state='jump'}
 move(c,to,dt,speed){c.routeAge-=dt;const p=this.point(c);if(c.routeAge<=0||!c.path.length||!c.lastGoal||distance(c.lastGoal,to)>1){c.path=findGridPath(p,to,this.blocked,{step:1,bound:42,maxNodes:12000});c.routeAge=2;c.lastGoal={...to}}while(c.path.length&&distance(p,c.path[0])<.3)c.path.shift();const target=c.path[0]||to,dx=target.x-p.x,dz=target.z-p.z,d=Math.hypot(dx,dz);if(d<.12)return false;const k=Math.min(speed*dt,d)/d,x=p.x+dx*k,z=p.z+dz*k;if(this.blocked(x,z)){c.routeAge=0;return false}c.g.position.set(x,this.terrain(x,z),z);c.g.rotation.y=Math.atan2(dx,dz);c.steps+=dt*speed*7;return true}
 update(dt,birds){if(!this.root.visible||!this.houses?.length)return;dt=Math.max(0,Math.min(.05,dt));this.time+=dt;for(const c of this.cats){c.timer-=dt;c.g.visible=c.state!=='hide'||c.timer>1.5;const p=this.point(c);let moving=false;if(c.jump){const j=c.jump;j.t+=dt/j.duration;const t=Math.min(1,j.t),k=t*t*(3-2*t);c.g.position.set(j.from.x+(j.to.x-j.from.x)*k,j.from.y+(j.to.y-j.from.y)*k+Math.sin(t*Math.PI)*1.2,j.from.z+(j.to.z-j.from.z)*k);c.g.rotation.y=Math.atan2(j.to.x-j.from.x,j.to.z-j.from.z);if(t>=1){c.jump=null;c.state=j.then;c.timer=5}moving=true}
 else if(c.index===0){const h=this.houses[c.home];if(c.state==='roof'||c.state==='hide'){if(c.timer<=0){if(c.state==='roof'){c.roofScratched=false;c.state='hide';c.timer=3;c.target={x:h.x-h.w*.28,y:h.y,z:h.z-h.d*.28}}else{const ground={x:h.exit.x,z:h.exit.z,y:this.terrain(h.exit.x,h.exit.z)};this.leap(c,ground,'travel');c.home=(c.home+1)%this.houses.length;this.stats.roofVisits++;c.path=[]}}else if(c.state==='roof'){if(!c.target||distance(p,c.target)<.15)c.target={x:h.x+Math.sin(this.time*.5)*h.w*.3,y:h.y,z:h.z+Math.cos(this.time*.5)*h.d*.3};moving=this.roofMove(c,c.target,dt)}else moving=this.roofMove(c,c.target,dt);const bird=birds.nearest?.(p.x,p.z,4,p.y+1.4);if(bird&&Math.abs(bird.y-p.y)<1.4){this.roofMove(c,{x:Math.max(h.x-h.w*.35,Math.min(h.x+h.w*.35,bird.x)),y:h.y,z:Math.max(h.z-h.d*.35,Math.min(h.z+h.d*.35,bird.z))},dt,3);if(distance(p,bird)<1.3){birds.scare(bird.index);c.chaseCount++;this.stats.chases++}}if(c.state==='roof'&&c.timer<2){c.legs[1].rotation.x=Math.sin(this.time*15)*.8;c.legs[3].rotation.x=-Math.sin(this.time*15)*.8;if(!c.roofScratched){c.roofScratched=true;c.scratchCount++;this.stats.scratches++}}if(c.state==='hide')c.body.rotation.x=-.12;else c.body.rotation.x=0}
 else{const approach=h.exit;moving=this.move(c,approach,dt,3.1);if(distance(this.point(c),approach)<.8)this.leap(c,{x:h.x,y:h.y,z:h.z},'roof',1.1)}}
 else{const bird=birds.nearest?.(p.x,p.z,8,1.4);if(bird&&c.state!=='approach'&&c.state!=='scratch'){c.state='hunt';c.target={x:bird.x,z:bird.z};moving=this.move(c,c.target,dt,4.2);if(distance(p,bird)<1.1){birds.scare(bird.index);c.chaseCount++;this.stats.chases++;this.leap(c,{x:p.x+Math.sin(c.g.rotation.y)*.7,y:this.terrain(p.x,p.z),z:p.z+Math.cos(c.g.rotation.y)*.7},'play',.45)}}else if(c.state==='scratch'){c.legs[1].rotation.x=Math.sin(this.time*15)*.9;c.legs[3].rotation.x=-Math.sin(this.time*15)*.9;c.body.rotation.x=-.2;if(c.timer<=0){c.state='play';c.timer=0;c.body.rotation.x=0}}
 else{if(c.timer<=0||!c.target){const i=Math.floor(this.time/5)%Math.max(1,this.objects.length),o=this.objects[i];if(o&&Math.floor(this.time/7)%3!==0){c.target={x:o.x+o.r+.45,z:o.z};c.object=o;c.state='approach'}else{c.state='play';c.target={x:Math.sin(this.time*.4)*32,z:Math.cos(this.time*.31)*32}}c.timer=c.state==='approach'?30:7}moving=this.move(c,c.target,dt,c.state==='play'?3.6:2.6);if(distance(this.point(c),c.target)<.95){if(c.state==='approach'){c.state='scratch';c.timer=2.5;c.g.rotation.y=Math.atan2(c.object.x-c.g.position.x,c.object.z-c.g.position.z);c.scratchCount++;this.stats.scratches++}else{c.timer=0;c.state='play'}}if(c.state==='hunt'){c.state='play';c.timer=0}}}
 c.tail.rotation.y=Math.sin(this.time*2+c.index)*.4;for(let i=0;i<c.legs.length;i++)if(c.state!=='scratch'&&!(c.state==='roof'&&c.timer<2))c.legs[i].rotation.x=moving?Math.sin(c.steps+i%2*Math.PI)*.65:0;c.head.rotation.y=c.state==='hide'?.35:Math.sin(this.time*.7)*.1}}
 roofMove(c,to,dt,speed=1.6){const p=this.point(c),d=distance(p,to),k=Math.min(1,speed*dt/Math.max(.001,d));c.g.position.x+=(to.x-p.x)*k;c.g.position.z+=(to.z-p.z)*k;c.g.rotation.y=Math.atan2(to.x-p.x,to.z-p.z);c.steps+=dt*speed*7;return d>.1}
 inspect(){return {visible:this.root.visible,count:this.root.visible?2:0,...this.stats,cats:this.cats.map(c=>({state:c.state,x:c.g.position.x,y:c.g.position.y,z:c.g.position.z,scratches:c.scratchCount,chases:c.chaseCount}))}}
}
