import {findGridPath} from './navigation.js?v=177';
import {capsuleAt,capsuleCircleContact} from './boar-physics.js?v=177';
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export class CatLife{
 constructor(T,scene,mobile=false){this.T=T;this.mobile=mobile;this.root=new T.Group();scene.add(this.root);this.root.visible=false;this.cats=[this.model(0),this.model(1)];this.time=0;this.stats={chases:0,scratches:0,roofVisits:0,boarGames:0,repairs:0}}
 model(index,parent=this.root){const T=this.T,g=new T.Group(),fur=new T.MeshLambertMaterial({color:index?0xc98445:0x555b65}),white=new T.MeshLambertMaterial({color:0xe8ded1}),pink=new T.MeshLambertMaterial({color:0xd99898}),black=new T.MeshBasicMaterial({color:0x16261b});parent.add(g);const box=(mat,x,y,z,w,h,d)=>{const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);g.add(m);return m};const body=box(fur,0,.4,0,.38,.34,.75),head=box(fur,0,.65,.42,.4,.36,.32);box(white,0,.31,.26,.26,.24,.18);for(const x of [-.13,.13]){const ear=new T.Mesh(new T.ConeGeometry(.11,.2,4),fur);ear.position.set(x,.94,.4);g.add(ear);box(black,x,.7,.59,.07,.065,.025)}box(pink,0,.59,.602,.07,.05,.025);const legs=[];for(const x of [-.13,.13])for(const z of [-.25,.25])legs.push(box(z>0?white:fur,x,.17,z,.12,.32,.13));const tail=new T.Group();tail.position.set(0,.48,-.4);g.add(tail);const tm=new T.Mesh(new T.BoxGeometry(.09,.09,.64),fur);tm.position.z=-.26;tail.add(tm);tail.rotation.x=-.5;g.traverse(o=>{if(o.isMesh){o.castShadow=!this.mobile;o.receiveShadow=!this.mobile}});return {g,body,head,legs,tail,index,state:index?'play':'roof',timer:0,path:[],routeAge:0,home:0,jump:null,target:null,steps:0,scratchCount:0,chaseCount:0}}

 reset(level,houses,objects,terrain,blocked){this.root.visible=level===3;this.time=0;this.terrain=terrain;this.blocked=blocked;this.houses=houses;this.objects=objects;this.stats={chases:0,scratches:0,roofVisits:0,boarGames:0,repairs:0};if(!this.root.visible||!houses.length)return;for(const c of this.cats){c.path=[];c.routeAge=0;c.lastGoal=null;c.timer=c.index?0:8;c.gameTimer=12+c.index*5;c.jump=null;c.target=null;c.boar=null;c.scratchCount=c.chaseCount=0;c.roofScratched=false;c.home=0;c.state=c.index?'play':'roof';c.g.visible=true;c.body.scale.y=1;const h=houses[0],ground=this.safeGround(h.exit);c.g.position.set(c.index?ground.x:h.x,c.index?terrain(ground.x,ground.z):h.y,c.index?ground.z:h.z);c.steps=0}}
 point(c){return {x:c.g.position.x,y:c.g.position.y,z:c.g.position.z}}
 safeGround(p){if(!this.blocked(p.x,p.z))return {x:p.x,z:p.z,y:this.terrain(p.x,p.z)};for(let r=.4;r<6;r+=.4)for(let i=0;i<24;i++){const a=i/24*Math.PI*2,x=p.x+Math.sin(a)*r,z=p.z+Math.cos(a)*r;if(!this.blocked(x,z))return {x,z,y:this.terrain(x,z)}}return {x:0,z:4,y:this.terrain(0,4)}}
 leap(c,to,then,duration=1){c.target=null;c.path=[];c.jump={from:this.point(c),to:{...to},t:0,duration,then};c.state='jump'}
 move(c,to,dt,speed){c.routeAge-=dt;const p=this.point(c);if(c.routeAge<=0||!c.path.length||!c.lastGoal||distance(c.lastGoal,to)>1){c.path=findGridPath(p,to,this.blocked,{step:.6,bound:42,maxNodes:14000});c.routeAge=2;c.lastGoal={...to}}while(c.path.length&&distance(p,c.path[0])<.25)c.path.shift();const target=c.path[0]||to,dx=target.x-p.x,dz=target.z-p.z,d=Math.hypot(dx,dz);if(d<.08)return false;const k=Math.min(speed*dt,d)/d,x=p.x+dx*k,z=p.z+dz*k;if(this.blocked(x,z)||(this.player&&Math.abs(this.terrain(x,z)-this.player.y)<1&&capsuleCircleContact(capsuleAt(x,z,Math.atan2(dx,dz),.4),this.player.x,this.player.z,.43))){c.routeAge=0;return false}c.g.position.set(x,this.terrain(x,z),z);c.g.rotation.y=Math.atan2(dx,dz);c.steps+=dt*speed*7;return true}
 roofMove(c,to,dt,speed=1.6){const h=this.houses[c.home],p=this.point(c);to={x:Math.max(h.x-h.w*.3,Math.min(h.x+h.w*.3,to.x)),z:Math.max(h.z-h.d*.3,Math.min(h.z+h.d*.3,to.z))};const d=distance(p,to),k=Math.min(1,speed*dt/Math.max(.001,d));c.g.position.set(p.x+(to.x-p.x)*k,h.y,p.z+(to.z-p.z)*k);c.g.rotation.y=Math.atan2(to.x-p.x,to.z-p.z);c.steps+=dt*speed*7;return d>.1}
 boarTop(b){return {x:b.g.position.x,y:b.g.position.y+1.17*Math.abs(b.g.scale.y),z:b.g.position.z}}
 beginBoarGame(c,boars){if(c.gameTimer>0||c.jump||['roof','hide','scratch','ride','boarPlay'].includes(c.state))return;const p=this.point(c),b=boars.filter(b=>!b.flee&&!b.attackLeap&&b.g.position.y>-.2&&distance(p,{x:b.g.position.x,z:b.g.position.z})<12).sort((a,b)=>distance(p,a.g.position)-distance(p,b.g.position))[0];if(b){c.boar=b;c.state='boarPlay';c.path=[];c.target=null;c.timer=9;c.gameTimer=18+c.index*7}else c.gameTimer=3}
 avoidPlayer(x,z,y,dt){if(!this.root.visible)return;for(const c of this.cats){if(c.jump||['roof','hide','ride'].includes(c.state)||Math.abs(c.g.position.y-y)>1)continue;const p=this.point(c),d=Math.hypot(p.x-x,p.z-z);if(d>2.0)continue;const a=Math.atan2(p.x-x,p.z-z);for(const turn of [0,.6,-.6,1.2,-1.2,Math.PI]){const step=Math.min(.2,dt*4.5),nx=p.x+Math.sin(a+turn)*step,nz=p.z+Math.cos(a+turn)*step;if(!this.blocked(nx,nz)&&Math.hypot(nx-x,nz-z)>d+.001){c.g.position.set(nx,this.terrain(nx,nz),nz);c.g.rotation.y=a+turn;c.steps+=step*7;c.routeAge=0;break}}}}
 blocks(x,z,y,radius=.43){return this.root.visible&&this.cats.some(c=>c.g.visible&&Math.abs(c.g.position.y-y)<.7&&capsuleCircleContact(capsuleAt(c.g.position.x,c.g.position.z,c.g.rotation.y,.4),x,z,radius))}
 update(dt,birds,boars=[],player=null){if(!this.root.visible||!this.houses?.length)return;dt=Math.max(0,Math.min(.05,dt));this.time+=dt;this.player=player;for(const c of this.cats){c.timer-=dt;c.gameTimer-=dt;c.g.visible=true;c.body.scale.y=c.state==='hide'?.65:1;const p=this.point(c);let moving=false;this.beginBoarGame(c,boars);
 if(c.jump){const j=c.jump;if(j.then==='ride'&&c.boar?.g)j.to=this.boarTop(c.boar);j.t+=dt/j.duration;const t=Math.min(1,j.t),k=t*t*(3-2*t);c.g.position.set(j.from.x+(j.to.x-j.from.x)*k,j.from.y+(j.to.y-j.from.y)*k+Math.sin(t*Math.PI)*1.6,j.from.z+(j.to.z-j.from.z)*k);c.g.rotation.y=Math.atan2(j.to.x-j.from.x,j.to.z-j.from.z);if(t>=1){c.jump=null;c.state=j.then;c.timer=c.state==='roof'?8:c.state==='ride'?2.3:5;c.target=null;c.routeAge=0}moving=true}
 else if(c.state==='boarPlay'){if(!c.boar?.g||c.boar.flee||c.timer<=0){c.boar=null;c.state=c.index?'play':'travel';c.target=null}else{const b=this.boarTop(c.boar);moving=this.move(c,b,dt,4);if(distance(this.point(c),b)<1.25){this.leap(c,b,'ride',.7);this.stats.boarGames++}}}
 else if(c.state==='ride'){if(c.boar?.g&&!c.boar.flee&&c.timer>0){const b=this.boarTop(c.boar);c.g.position.set(b.x,b.y,b.z);c.g.rotation.y=c.boar.g.rotation.y;c.legs[1].rotation.x=Math.sin(this.time*18)*.6;c.legs[3].rotation.x=-Math.sin(this.time*18)*.6;if(!c.rideScratched){c.rideScratched=true;c.scratchCount++;this.stats.scratches++}}else{const ground=this.safeGround({x:p.x+2,z:p.z+1});c.rideScratched=false;c.boar=null;this.leap(c,ground,c.index?'play':'travel',.65)}}
 else if(c.index===0){const h=this.houses[c.home];if(c.state==='roof'||c.state==='hide'){if(c.timer<=0){if(c.state==='roof'){c.roofScratched=false;c.state='hide';c.timer=3;c.target={x:h.x-h.w*.25,z:h.z-h.d*.25}}else{this.leap(c,this.safeGround(h.exit),'travel');c.home=(c.home+1)%this.houses.length;this.stats.roofVisits++}}else{if(!c.target||distance(p,c.target)<.15)c.target=c.state==='hide'?{x:h.x-h.w*.25,z:h.z-h.d*.25}:{x:h.x+Math.sin(this.time*.5)*h.w*.28,z:h.z+Math.cos(this.time*.5)*h.d*.28};moving=this.roofMove(c,c.target,dt);if(c.state==='roof'){const bird=birds.nearest?.(p.x,p.z,4,p.y+1.4);if(bird&&Math.abs(bird.y-p.y)<1.4){moving=this.roofMove(c,bird,dt,3);if(distance(p,bird)<1.3){birds.scare(bird.index);c.chaseCount++;this.stats.chases++}}if(c.timer<2){c.legs[1].rotation.x=Math.sin(this.time*15)*.8;c.legs[3].rotation.x=-Math.sin(this.time*15)*.8;if(!c.roofScratched){c.roofScratched=true;c.scratchCount++;this.stats.scratches++}}}}}else{const approach=this.safeGround(h.exit);moving=this.move(c,approach,dt,3.1);if(distance(this.point(c),approach)<.6)this.leap(c,{x:h.x,y:h.y,z:h.z},'roof',1.1)}}
 else{const bird=birds.nearest?.(p.x,p.z,8,1.4);if(bird&&!['approach','scratch'].includes(c.state)){c.state='hunt';c.target={x:bird.x,z:bird.z};moving=this.move(c,c.target,dt,4.2);if(distance(p,bird)<1.1){birds.scare(bird.index);c.chaseCount++;this.stats.chases++;this.leap(c,this.safeGround({x:p.x+Math.sin(c.g.rotation.y)*.7,z:p.z+Math.cos(c.g.rotation.y)*.7}),'play',.45)}}else if(c.state==='scratch'){c.legs[1].rotation.x=Math.sin(this.time*15)*.9;c.legs[3].rotation.x=-Math.sin(this.time*15)*.9;c.body.rotation.x=-.2;if(c.timer<=0){c.state='play';c.timer=0;c.body.rotation.x=0}}
 else{if(c.timer<=0||!c.target){const i=Math.floor(this.time/5)%Math.max(1,this.objects.length),o=this.objects[i];if(o&&Math.floor(this.time/7)%3!==0){c.target=this.safeGround({x:o.x+o.r+.45,z:o.z});c.object=o;c.state='approach'}else{c.state='play';c.target=this.safeGround({x:Math.sin(this.time*.4)*32,z:Math.cos(this.time*.31)*32})}c.timer=c.state==='approach'?30:7}moving=this.move(c,c.target,dt,c.state==='play'?3.6:2.6);if(distance(this.point(c),c.target)<.95){if(c.state==='approach'){c.state='scratch';c.timer=2.5;c.g.rotation.y=Math.atan2(c.object.x-c.g.position.x,c.object.z-c.g.position.z);c.scratchCount++;this.stats.scratches++}else{c.timer=0;c.state='play'}}if(c.state==='hunt'){c.state='play';c.timer=0}}}
 this.validateSupport(c);c.tail.rotation.y=Math.sin(this.time*2+c.index)*.4;for(let i=0;i<c.legs.length;i++)if(!['scratch','ride'].includes(c.state)&&!(c.state==='roof'&&c.timer<2))c.legs[i].rotation.x=moving?Math.sin(c.steps+i%2*Math.PI)*.65:0;c.head.rotation.y=c.state==='hide'?.35:Math.sin(this.time*.7)*.1}
 if(player)this.avoidPlayer(player.x,player.z,player.y,dt)}
 validateSupport(c){if(c.jump||c.state==='ride')return;const p=this.point(c);if(!Number.isFinite(p.x+p.y+p.z)){const h=this.houses[c.home];c.g.position.set(h.x,h.y,h.z);c.state='roof';c.timer=5;this.stats.repairs++;return}if(['roof','hide'].includes(c.state)){const h=this.houses[c.home];c.g.position.x=Math.max(h.x-h.w*.3,Math.min(h.x+h.w*.3,p.x));c.g.position.z=Math.max(h.z-h.d*.3,Math.min(h.z+h.d*.3,p.z));c.g.position.y=h.y}else{c.g.position.y=this.terrain(p.x,p.z);if(this.blocked(p.x,p.z)){const q=this.safeGround(p);c.g.position.set(q.x,q.y,q.z);c.path=[];c.routeAge=0;this.stats.repairs++}}}
 inspect(){return {visible:this.root.visible,count:this.root.visible?2:0,...this.stats,cats:this.cats.map(c=>({state:c.state,visible:c.g.visible,x:c.g.position.x,y:c.g.position.y,z:c.g.position.z,home:c.home,jumping:!!c.jump,scratches:c.scratchCount,chases:c.chaseCount}))}}
}
