// A shared, bounded mix for synthesized effects, ambience and the existing score.
export class Soundscape{
 constructor(context){this.context=context;const c=context;this.master=c.createGain();this.master.gain.value=.82;this.limiter=c.createDynamicsCompressor();this.limiter.threshold.value=-18;this.limiter.knee.value=12;this.limiter.ratio.value=5;this.limiter.attack.value=.008;this.limiter.release.value=.22;this.master.connect(this.limiter).connect(c.destination);this.effects=c.createGain();this.music=c.createGain();this.ambience=c.createGain();this.effects.gain.value=.9;this.music.gain.value=.62;this.ambience.gain.value=.7;for(const bus of [this.effects,this.music,this.ambience])bus.connect(this.master);this.cooldowns=new Map();this.voices=new Set();this.distance=0;this.lastPosition=null;this.lastWater=false;this.noiseBuffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate);const d=this.noiseBuffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;
 this.beds={};for(const [name,cutoff] of [['wind',380],['rain',1800],['water',700]]){const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noiseBuffer;n.loop=true;f.type='lowpass';f.frequency.value=cutoff;g.gain.value=0;n.connect(f).connect(g).connect(this.ambience);n.start();this.beds[name]=g}
 }
 noise(duration,gain,cutoff=800,delay=0){if(this.voices.size>=24)return;const c=this.context,t=c.currentTime+delay,n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noiseBuffer;n.loop=true;f.type='lowpass';f.frequency.value=cutoff;g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(Math.min(.055,gain),t+.018);g.gain.exponentialRampToValueAtTime(.0001,t+duration);n.connect(f).connect(g).connect(this.effects);this.voices.add(n);n.onended=()=>{this.voices.delete(n);n.disconnect();f.disconnect();g.disconnect()};n.start(t);n.stop(t+duration+.02)}
 event(name){const now=this.context.currentTime;if(now<(this.cooldowns.get(name)||0))return;this.cooldowns.set(name,now+({step:.12,hoof:.12,splash:.22,fire:.5,thunder:2}[name]||.08));const sounds={step:[.09,.016,900],snowstep:[.14,.018,2100],leafstep:[.14,.017,1600],hoof:[.1,.023,420],splash:[.35,.025,1500],throw:[.16,.019,1200],land:[.12,.022,600],mount:[.17,.023,400],eat:[.18,.018,850],fire:[.38,.024,650],thunder:[1.8,.045,230],portal:[.65,.027,1100]};const s=sounds[name];if(name==='lightning'){this.noise(.13,.035,3400);return}if(name==='thunder'){this.noise(3.6,.09,180,.18);this.noise(2.4,.045,480,.7);this.noise(1.8,.025,110,1.5);return}if(s)this.noise(...s)}
 update({active,sfx,music,season,stage,water,mounted,x,z,grounded,dt}){const c=this.context;this.effects.gain.setTargetAtTime(sfx?.9:0,c.currentTime,.025);this.music.gain.setTargetAtTime(music?.62:0,c.currentTime,.08);const audible=active&&sfx;const levels={wind:audible?(season==='winter'?.014:.003+stage*.002):0,rain:audible&&season!=='winter'?stage*.005:0,water:audible&&water?.009:0};for(const [k,g] of Object.entries(this.beds))g.gain.setTargetAtTime(levels[k],c.currentTime,.3);
 if(!active){this.lastPosition=null;this.distance=0;this.lastWater=false;return}if(this.lastPosition){const d=Math.hypot(x-this.lastPosition.x,z-this.lastPosition.z);if(d<2)this.distance+=d;else this.distance=0}this.lastPosition={x,z};if(water!==this.lastWater&&sfx)this.event('splash');this.lastWater=water;if(grounded&&this.distance>(mounted?.95:.78)){this.distance=0;if(sfx){if(water)this.event('splash');else if(mounted)this.event('hoof');else if(season==='winter')this.event('snowstep')}}
 }
}
